<a href="https://colab.research.google.com/github/bhanuprakash227/DataScience_ExcelR_Assignments/blob/main/2_Datastrutures_functions_numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Section A — Data Structures & Control Structures**

**1: List Operations**

In [1]:
numbers = [50, 20, 40, 20, 10]
print("Original List:", numbers)

numbers.append(60)
print("After append:", numbers)

numbers.extend([70, 80])
print("After extend:", numbers)

numbers.insert(1, 25)
print("After insert:", numbers)

numbers.remove(20)
print("After remove:", numbers)

removed_element = numbers.pop()
print("Popped element:", removed_element)
print("After pop:", numbers)

print("Index of 40:", numbers.index(40))

print("Count of 20:", numbers.count(20))

numbers.sort()
print("After sort:", numbers)

numbers.reverse()
print("After reverse:", numbers)

numbers.clear()
print("After clear:", numbers)

Original List: [50, 20, 40, 20, 10]
After append: [50, 20, 40, 20, 10, 60]
After extend: [50, 20, 40, 20, 10, 60, 70, 80]
After insert: [50, 25, 20, 40, 20, 10, 60, 70, 80]
After remove: [50, 25, 40, 20, 10, 60, 70, 80]
Popped element: 80
After pop: [50, 25, 40, 20, 10, 60, 70]
Index of 40: 2
Count of 20: 1
After sort: [10, 20, 25, 40, 50, 60, 70]
After reverse: [70, 60, 50, 40, 25, 20, 10]
After clear: []


**2:Tuple**

In [2]:
students = ("Rahul", "Priya", "Arun")
print("Original Tuple:", students)

try:
    students[1] = "Bhanu"
except TypeError as e:
    print("Error:", e)

print("\nExplanation:")
print("Tuples are immutable, so their elements cannot be changed after creation.")

Original Tuple: ('Rahul', 'Priya', 'Arun')
Error: 'tuple' object does not support item assignment

Explanation:
Tuples are immutable, so their elements cannot be changed after creation.


**3:Set**

In [3]:
numbers = {10, 20, 30, 20, 40, 10, 50, 30}

print("Set:", numbers)

print("\nExplanation:A set automatically removes duplicate values.Therefore, each value appears only once.")

Set: {50, 20, 40, 10, 30}

Explanation:A set automatically removes duplicate values.Therefore, each value appears only once.


**4:Dictionary**

In [4]:
student = {
    "name": "Bhanu",
    "age": 22,
    "city": "Warangal"
}
student["age"] = 23
student["email"] = "bhanu@gmail.com"

print("Final Dictionary:")
print(student)

Final Dictionary:
{'name': 'Bhanu', 'age': 23, 'city': 'Warangal', 'email': 'bhanu@gmail.com'}


**5:Voting Elgibility**

In [10]:
age =int(input("Enter the age:"))
if age >= 18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")

Enter the age:22
The person is eligible to vote.


**6:Grade**

In [9]:
marks =int(input("Enter the marks:"))
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"
print("Marks:", marks)
print("Grade:", grade)

Enter the marks:66
Marks: 66
Grade: C


**7:Positive,Negitive or Zero**

In [8]:
number = int(input("Enter a number: "))
if number > 0:
    print("The number is positive.")
    if number % 2 == 0:
        print("The number is even.")
    else:
        print("The number is odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number: 0
The number is zero.


#**Section B — NumPy**

**NumPy Arrays**

In [11]:
import numpy as np
scalar = np.array(5)                      #scaler
array_1d = np.array([1, 2, 3, 4, 5])      #1D
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])                                        #2d

print("Scalar:")
print(scalar)

print("\n1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


**Random 4×4 NumPy Array**

In [12]:
import numpy as np

random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[40 42 95 31]
 [45 84 22 22]
 [80  7 41 73]
 [54 46 28 32]]


**NumPy to Pandas DataFrame**

In [13]:
import numpy as np
import pandas as pd
array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
df = pd.DataFrame(array, columns=["A", "B", "C"])
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


#**Section C — Exploring Pandas**

**Pandas DataFrame Operations**

In [15]:
import pandas as pd
import numpy as np
data = {
    "Name": [
        "Rahul", "Priya", "Arun", "Bhanu", "Sneha",
        "Kiran", "Anjali", "Vijay", "Rahul", "Priya"
    ],

    "Age": [
        22, 24, 23, 25, 21,
        26, 24, 27, 22, 24
    ],

    "City": [
        "Warangal", "Hyderabad", "Delhi", "Warangal", "Mumbai",
        "Chennai", "Hyderabad", "Bangalore", "Warangal", "Hyderabad"
    ],

    "Salary": [
        30000, 35000, np.nan, 40000, 28000,
        45000, 38000, np.nan, 30000, 35000
    ]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

print("\n--- DataFrame Information ---")
df.info()

print("\n--- Statistical Description ---")
print(df.describe())

print("\n--- Name and City Columns ---")
print(df[["Name", "City"]])

salary_mean = df["Salary"].mean()

df["Salary"] = df["Salary"].fillna(salary_mean)

print("\n--- After Filling Missing Salary Values ---")
print(df)

df = df.drop_duplicates()

print("\n--- After Removing Duplicate Rows ---")
print(df)

df = df.drop("City", axis=1)

print("\n--- Final DataFrame After Dropping City ---")
print(df)

Original DataFrame:
     Name  Age       City   Salary
0   Rahul   22   Warangal  30000.0
1   Priya   24  Hyderabad  35000.0
2    Arun   23      Delhi      NaN
3   Bhanu   25   Warangal  40000.0
4   Sneha   21     Mumbai  28000.0
5   Kiran   26    Chennai  45000.0
6  Anjali   24  Hyderabad  38000.0
7   Vijay   27  Bangalore      NaN
8   Rahul   22   Warangal  30000.0
9   Priya   24  Hyderabad  35000.0

--- DataFrame Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

--- Statistical Description ---
             Age      Salary
count  10.000000      8.0000
mean   23.800000  35125.0000
std     1.873796   5767.8295
min    21.000000  28000.0